### ISSUE TITLE
AOM tab needs reloading on startup for ACR entries to appear

### ISSUE THREAD

**Issue by brianking** [mozilla/ACR#19]
I don't know how important this is, but if about:addons is 
   open at startup (which it always is in my test profile), the 
   add-on item context menu entries for the ACR don't appear. 
   The tab needs to be reloaded first.

**Comment by tofumatt** [comment]
Is this still reproducible?

**Comment by wagnerand** [comment]
I tried this last week and couldn't reproduce.
