### ISSUE TITLE
dialog from about:addons shows scrollbars

### ISSUE THREAD

**Issue by Jan02** [mozilla/ACR#23]
https://bugzilla.mozilla.org/show_bug.cgi?id=1193719

install [compatibility reporter addon] (https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter/)
report an issue from  about:addons
[dialog shows scrollbars] (http://i.imgur.com/fJKPUwx.png)

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0

**Comment by kmaglione** [comment]
I prefer to keep issues on Bugzilla.

**Comment by jvillalobos** [comment]
My bad!
