### ISSUE TITLE
Add in e10s status of add-on

### ISSUE THREAD

**Issue by andymckay** [mozilla/ACR#26]
An add-on can have the multiProcessCompatible flag to true or not. It looks like the code:

https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/internal/XPIProvider.jsm#793

Might tell us, if we've already got the add-on. Although there are 3 states: true, false and unset.

Supports mozilla/addons#163

**Comment by wagnerand** [comment]
I'm taking this.
