### ISSUE TITLE
Add-on icons in panel are broken

### ISSUE THREAD

**Issue by wagnerand** [mozilla/ACR#32]
Because the panel does not have access to URLs like `jar:file:///var/folders/lq/xzbvpxjs4bj_m83qqkkn0bx40000gn/T/589bb220-5407-4242-80b2-f1b38fc481ca/extensions/compatibility@addons.mozilla.org.xpi!/icon.png`.

One idea would be to XHR the icon from `lib/main.js` and use the _base64_ string of it...

**Comment by tofumatt** [comment]
Having the icon appear would be nice and it's not THAT big, so XHRing it works for me.

**Comment by wagnerand** [comment]
The problem with XHR'ing though is that `sendAddonReports` is not async-ready, so we either have to rewrite quite a bit or use sync XHRs.

(Note: Reviewers are supposed to deny full-review for sync XHRs even if they are local, for performance reasons).

**Comment by tofumatt** [comment]
Do you mean https://github.com/mozilla/ACR/blob/2b03763d0bfa72afbb966ae493791acf4195ad96/lib/main.js#L248 ?

Seems like it would be easy to add an async call there and then run the rest once it's done, if that's all you mean.

**Comment by wagnerand** [comment]
Yes, that's the code.

Sorry, I don't see how it's that easy. The XHR needs to happen inside the `for` loop, but https://github.com/mozilla/ACR/blob/2b03763d0bfa72afbb966ae493791acf4195ad96/lib/main.js#L264 needs to happen once after the for loop (and all XHR callbacks) are done.

**Comment by tofumatt** [comment]
Oh, I see. I suppose you could do an XHR for each one, then wait for them all to be loaded at the end before displaying. e.g.:

```js
if (reportsProcessed === addonReports.length) {
    reporterPanel.port.emit("have_addon_reports", addonReports);
}
```

at the end of the loop? It's hacky but it'd work.

Maybe we can at least use a puzzle piece or something generic if we can’t load the icon?

**Comment by wagnerand** [comment]
Yeah I see no other way than adding another counter.

Adding a generic icon is possible. We already use one if the add-on doesn't have an icon, but I'd like to avoid that, because we should show the real icon if there is one.
