### ISSUE TITLE
Panel size are incorrect in ACR 2.1.0

### ISSUE THREAD

**Issue by yfdyh000** [mozilla/ACR#37]
See screenshots:
![2.0.6.1-signed.1-signed](https://cloud.githubusercontent.com/assets/1769875/17216901/18217d38-5515-11e6-891e-e7d88992c615.png)
![2.1.0](https://cloud.githubusercontent.com/assets/1769875/17216902/18a82482-5515-11e6-8433-9677938be380.png)

**Comment by wagnerand** [comment]
Thank you for your report! I don't see an issue in the first screenshot.
The second screenshot seems odd though. What operating system and version is this?

**Comment by yfdyh000** [comment]
The first screenshot is 2.0.6.1-signed.1-signed.
The second screenshot is 2.1.0 with Fx48 x64 on Win10, and items with vertical scrollbar.

**Comment by wagnerand** [comment]
Interesting, two people tested this on Windows 10. I will look into it.

**Comment by wagnerand** [comment]
This has been fixed in #38. A new version has been released and should be available shortly.

Thank you again!

**Comment by yfdyh000** [comment]
It does not restore the original height (first screenshot). This is an expected change?

**Comment by wagnerand** [comment]
The height calculation is not trivial and I didn't look into that very much. I merely fixed the design glitches. Can you confirm they are gone?

**Comment by yfdyh000** [comment]
The 2.1.* have one and half items height, like the second screenshot.
